### ISSUE TITLE
Regression in 11.1.0+ (also reproduced in 12.0.0) 

### ISSUE THREAD

**Issue by Tanneguy** [elm-athlete/athlete#14]
I get the following error message with elm-reactor on a lightweight code [OrdList.elm.tar.gz](https://github.com/elm-bodybuilder/elegant/files/1506798/OrdList.eqslm.tar.gz) 

```
elm-make: Used toSrcType on a type that is not well-formed
elm-make: thread blocked indefinitely in an MVar operation
```

**Comment by Tanneguy** [comment]
This issue is relevant only to the code provided. So it is not an emergency.
But since the error message is really not usable by a user of the elegant library I still think it can be considered as serious.

**Comment by ghivert** [comment]
I found the error. It's mainly a problem with the elm-compiler which is really not clear when doing something like this. Generally, removing functions signatures help to solve it.

    onReturn : (String -> Msg) -> Modifiers.Modifier (OnEvent Msg String)

Should be:

    onReturn : (String -> Msg) -> Modifiers.Modifier (OnEvent Msg extendable)

Here, the extendable illustrates the others fields: by using extendable, you say to the compiler 'Ok, you can use this function on every element which handle events, among other attributes'.

**Comment by Tanneguy** [comment]
So
- the problem is with the compiler that should provide better messages
- whenever it happens, removing type signatures will alleviate the problem
  To find the correct signature, one can give an utterly incorrect one like 'Bool'
  There the compiler will complain by giving the actual signature inferred from the implementation

**Comment by ghivert** [comment]
Yep, the hard part is finding the bad signature.
